language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

dist: trusty
sudo: false

matrix:
  allow_failures:
    - php: nightly

services:
  - mysql

git:
  depth: 3

cache:
    directories:
        - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || true
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - mysql -e 'CREATE DATABASE IF NOT EXISTS travis;'

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer require --dev friendsofphp/php-cs-fixer phpmd/phpmd --prefer-dist --no-suggest --ansi
  - php bin/console doctrine:database:create --env=test --if-not-exists
  - php bin/console doctrine:migrations:migrate --no-interaction
  - php bin/console doctrine:fixtures:load --env=test --no-interaction
  - php bin/console mediaarea:user:donor test@mediaarea.net 1
  - php bin/console fos:user:create beta beta@mediaarea.net betaTravis
  - php bin/console fos:user:promote beta ROLE_BETA
  - php bin/console mediaarea:user:donor beta@mediaarea.net 30

script:
  - ./vendor/bin/simple-phpunit -v
  - vendor/bin/php-cs-fixer --dry-run --stop-on-violation --using-cache=no fix src/
  - vendor/bin/phpmd src/ text phpmd.xml
  - php bin/console lint:twig app/ src/
#  - php bin/console lint:xliff src/
  - php bin/console lint:xliff app/
  - php bin/console lint:yaml src/
  - php bin/console lint:yaml app/
