easy_admin:
    site_name: MediaArea Admin
    list:
        max_results: 50

    entities:
        User:
            class: UserBundle\Entity\User
            disabled_actions: ['new']
            search:
                fields: ['username', 'email', 'name']
            list:
                fields: ['username', { property: 'email', type: 'email' }, 'name', 'enabled', 'createdAt', 'lastLogin', { property: 'totalDonated', label: 'Total' }, 'vote']
            form:
                fields:
                    - 'username'
                    - { property: 'email', type: 'email' }
                    - 'name'
                    - 'companyName'
                    - 'newsletter'
                    - { property: 'professional', type: 'UserBundle\Form\Type\ProfessionalType' }
                    - { property: 'country', type: 'UserBundle\Form\Type\CountryCustomType' }
                    - { property: 'language', type: 'UserBundle\Form\Type\LanguageCustomType' }
                    - 'enabled'
                    - 'totalDonated'
                    - 'vote'
                    - 'displayName'
                    - 'endDate'
                    - 'roles'

        Invoice:
            class: PaymentBundle\Entity\Invoice
            disabled_actions: ['new', 'show', 'delete']
            search:
                fields: ['user', 'amount', 'vat', 'currency', 'ipAddress', 'country', 'date']
            list:
                fields:
                    - 'user'
                    - 'amount'
                    - 'vat'
                    - 'currency'
                    - 'ipAddress'
                    - 'country'
                    - 'date'
                    - { property: 'ShortPaymentSystemName', label: 'Payment' }
            form:
                fields:
                    - 'user'

        Feature:
            class: VoteBundle\Entity\Feature
            search:
                fields: ['title', 'description']
            list:
                fields: ['title', 'votesTarget', 'votesCountCache', 'status']
            form:
                fields:
                    - 'title'
                    - 'description'
                    - { property: 'votesTarget', type: 'integer', type_options: {'attr': {'min': 0}} }
                    - { property: 'votesCountCache', type: 'integer', type_options: {'attr': {'min': 0}} }
                    - { property: 'status', type: 'integer', type_options: {'attr': {'min': 0, 'max': 3}}, help: 'Close : 0 - Open : 1 - In progress : 2 - Finish : 3' }

        Vote:
            class: VoteBundle\Entity\Vote
            disabled_actions: ['new', 'show', 'delete', 'edit']
            search:
                fields: ['user', 'points', 'date']
            list:
                fields:
                    - 'user'
                    - 'points'
                    - 'date'
                    - 'feature'
