easy_admin:
    site_name: MediaArea Admin
    entities:
        User:
            class: UserBundle\Entity\User
            disabled_actions: ['new']
            search:
                fields: ['username', 'email', 'name']
            list:
                fields: ['username', { property: 'email', type: 'email' }, 'name', 'enabled', 'createdAt', 'lastLogin', { property: 'totalDonated', label: 'Total' }]
            form:
                fields:
                    - 'username'
                    - { property: 'email', type: 'email' }
                    - 'name'
                    - 'companyName'
                    - 'newsletter'
                    - { property: 'professional', type: 'UserBundle\Form\Type\ProfessionalType' }
                    - { property: 'country', type: 'UserBundle\Form\Type\CountryCustomType' }
                    - { property: 'language', type: 'UserBundle\Form\Type\LanguageCustomType' }
                    - 'enabled'
                    - 'totalDonated'
                    - 'vote'
                    - 'displayName'
                    - 'endDate'
                    - 'roles'

        Invoice:
            class: PaymentBundle\Entity\Invoice
            disabled_actions: ['new', 'show', 'edit', 'delete']
            search:
                fields: ['user', 'amount', 'vat', 'currency', 'ipAddress', 'country', 'date']
            list:
                fields: ['user', 'amount', 'vat', 'currency', 'ipAddress', 'country', 'date']
