dv_analyzer:
    resource: "@DVAnalyzerBundle/Controller/"
    type:     annotation

qc_tools:
    resource: "@QCToolsBundle/Controller/"
    type:     annotation

bwf_meta_edit:
    resource: "@BWFMetaEditBundle/Controller/"
    type:     annotation

media_trace:
    resource: "@MediaTraceBundle/Controller/"
    type:     annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation
