fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user:
    resource: "@UserBundle/Controller/"
    type:     annotation

avi_meta_edit:
    resource: "@AVIMetaEditBundle/Controller/"
    type:     annotation

ollistd:
    resource: "@OllistdBundle/Controller/"
    type:     annotation

dv_analyzer:
    resource: "@DVAnalyzerBundle/Controller/"
    type:     annotation

qc_tools:
    resource: "@QCToolsBundle/Controller/"
    type:     annotation

bwf_meta_edit:
    resource: "@BWFMetaEditBundle/Controller/"
    type:     annotation

media_trace:
    resource: "@MediaTraceBundle/Controller/"
    type:     annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation

media_info:
    resource: "@MediaInfoBundle/Controller/"
    type:     annotation
