services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MediaBinBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests}'

    MediaBinBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    MediaBinBundle\Lib\File\ExternalFile:
        arguments:
            $conf: '%mediabin.external%'

    MediaBinBundle\Lib\File\LocalFile:
        arguments:
            $conf: '%mediabin.local%'
