services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    UserBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Repository,Tests,Controller}'

    UserBundle\Controller\UserController:
        tags: ['controller.service_arguments']

    fos_user.registration.controller:
        class: UserBundle\Controller\RegistrationController
        arguments:
            - "@event_dispatcher"
            - "@fos_user.registration.form.factory"
            - "@fos_user.user_manager"
            - "@security.token_storage"

    fos_user.resetting.controller:
        class: UserBundle\Controller\ResettingController
        arguments:
            - "@event_dispatcher"
            - "@fos_user.resetting.form.factory"
            - "@fos_user.user_manager"
            - "@fos_user.util.token_generator"
            - "@fos_user.mailer"
            - "%fos_user.resetting.retry_ttl%"

    fos_user.security.controller:
        class: UserBundle\Controller\SecurityController
        arguments:
            - "@security.csrf.token_manager"

    user.util.donor_manipulator:
        class: UserBundle\Lib\DonorManipulator
        arguments: ["@fos_user.user_manager", "@fos_user.util.token_generator"]
        public: true

    UserBundle\Lib\Quotas\Quotas:
        lazy: true
        arguments:
            $options: '%mco.mediaconch.quotas%'

    Symfony\Component\Security\Http\RememberMe\RememberMeServicesInterface: '@security.authentication.rememberme.services.simplehash.main'

    UserBundle\EventSubscriber\GuestSubscriber:
        arguments:
            - "%fos_user.firewall_name%"
