services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    user.util.donor_manipulator:
        class: UserBundle\Lib\DonorManipulator
        arguments: ["@fos_user.user_manager", "@fos_user.util.token_generator", "@validator"]
