services:
#    bwf_meta_edit.example:
#        class: BWFMetaEditBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    bwf.download_info:
        class: BWFMetaEditBundle\Lib\DownloadInfo\BWFMetaEditDownloadInfo
        public: true
