services:
#    avi_meta_edit.example:
#        class: AVIMetaEditBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


    avi.download_info:
        class: AVIMetaEditBundle\Lib\DownloadInfo\AVIMetaEditDownloadInfo
        public: true
